#pragma config(Sensor, in1,    FourBar,        sensorPotentiometer)
#pragma config(Sensor, in2,    ,               sensorPotentiometer)
#pragma config(Sensor, dgtl1,  Wheels,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  Mobile,         sensorQuadEncoder)
#pragma config(Motor,  port1,           Mogo,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FrontBackLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FrontBackRight, tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FourBarLeft,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           FourBarRight,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           FourBarLeft2,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           FourBarRight2, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           ChainLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ChainRight,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Claw,          tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

//FourBarMovement

void fourbarup()
{
	SensorValue[FourBar] = 0;

	while(SensorValue(FourBar) <  180)
	{
	motor[Mogo] = 	-90;
	motor[Mogo] = 90;
	}
	motor[Mogo] = 	0;
	motor[Mogo] = 0;
}

void fourbardown()
{
	SensorValue[FourBar] = 0;

	while(SensorValue(FourBar) > 20)
	{
	motor[Mogo] = 90;
	motor[Mogo] = -90;
	}
	motor[Mogo] = 0;
	motor[Mogo] = 0;
}

//MobileGoalMovement

void mogodown()
{
	SensorValue[Mobile] = 0;

	while(SensorValue(Mobile) > 20)
	{
	motor[Mogo] = 90;
	motor[Mogo] = -90;
	}
	motor[Mogo] = 0;
	motor[Mogo] = 0;
}

void mogoup()
{
	SensorValue[Mobile] = 0;

	while(SensorValue(Mobile) > 20)
	{
	motor[Mogo] = 90;
	motor[Mogo] = -90;
	}
	motor[Mogo] = 0;
	motor[Mogo] = 0;
}

//Movement

void Moveforward()
{
	SensorValue[Wheels] = 0;

	while(SensorValue(Wheels) > 20)
	{
	motor[FrontBackLeft] = 90;
	motor[FrontBackRight] = -90;
	}
	motor[FrontBackLeft] = 0;
	motor[FrontBackRight] = 0;
}

void Movebackward()
{
	SensorValue[Wheels] = 0;

	while(SensorValue(Wheels) > 20)
	{
	motor[FrontBackLeft] = 90;
	motor[FrontBackRight] = 90;
	}
	motor[FrontBackLeft] = 0;
	motor[FrontBackRight] = 0;
}

void Left()
{
	SensorValue[Wheels] = 0;

	while(SensorValue(Wheels) > 20)
	{
	motor[FrontBackLeft] = -90;
	motor[FrontBackRight] = 90;
	}
	motor[FrontBackLeft] = 0;
	motor[FrontBackRight] = 0;
}

void Right()
{
	SensorValue[Wheels] = 0;

	while(SensorValue(Wheels) > 20)
	{
	motor[FrontBackLeft] = 90;
	motor[FrontBackRight] = -90;
	}
	motor[FrontBackLeft] = 0;
	motor[FrontBackRight] = 0;
}

void chainbarup(int time)
{
	motor[ChainLeft] = -127;
	motor[ChainRight] = -127;
}

void chainbardown(int time)
{
	motor[ChainLeft] = 127;
	motor[ChainRight] = -127;
}

void clawopen(int time)
{
	motor[Claw] = -127;
}

void clawclose(int time)
{
	motor[Claw] = 127;
}


	void pre_auton()
	{
		// Set bStopTasksBetweenModes to false if you want to keep user created tasks
		// running between Autonomous and Driver controlled modes. You will need to
		// manage all user created tasks if set to false.
		bStopTasksBetweenModes = true;

		// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
		// used by the competition include file, for example, you might want
		// to display your team name on the LCD in this function.
		// bDisplayCompetitionStatusOnLcd = false;

		// All activities that occur before the competition starts
		// Example: clearing encoders, setting servo positions, ...
	}


	/*---------------------------------------------------------------------------*/
	/*                                                                           */
	/*                              Autonomous Task                              */
	/*                                                                           */
	/*  This task is used to control your robot during the autonomous phase of   */
	/*  a VEX Competition.                                                       */
	/*                                                                           */
	/*  You must modify the code to add your own robot specific commands here.   */
	/*---------------------------------------------------------------------------*/



	task autonomous()
	{
		motor[FrontBackLeft] = 127;
		motor[FrontBackRight] = 127;
		wait1Msec(4000);
	}
	/*---------------------------------------------------------------------------*/
	/*                                                                     */
	/*                              User Control Task                            */
	/*                                                                           */
	/*  This task is used to control your robot during the user control phase of */
	/*  a VEX Competition.                                                       */
	/*                                                                           */
	/*  You must modify the code to add your own robot specific commands here.   */
	/*---------------------------------------------------------------------------*/

	task usercontrol()
	{
		// User control code here, inside the loop

		while (true)
		{
			//Movement
			motor[FrontBackRight] = (vexRT[Ch3] - vexRT[Ch4]);
			motor[FrontBackLeft]  = (vexRT[Ch3] + vexRT[Ch4]);

			//Mogo
			if(vexRT[Btn5U] == 1)
			{
				motor[Mogo] = 127;
			}
			else if(vexRT[Btn6U] == 1)
			{
				motor[Mogo] = -127;
			}
			else
			{
				motor[Mogo] = 0;
			}

			//Claw
			if(vexRT[Btn8D] == 1)
			{
				motor[Claw] = 120;
			}
			else if(vexRT[Btn8R] == 1)
			{
				motor[Claw] = -120;
			}
			else
			{
				motor[Claw] = 0;
			}

			//FourBar

			motor[FourBarLeft] = (vexRT[Ch3Xmtr2]);
			motor[FourBarRight] = (vexRT[Ch3Xmtr2]);
			motor[FourBarLeft2] = -(VexRT[Ch3Xmtr2]);
			motor[FourBarRight2] = -(vexRT[Ch3Xmtr2]);

			//ChainBar

			if(vexRT[Btn5UXmtr2] == 1)
			{
				motor[ChainLeft] = 120;
				motor[ChainRight] = 120;
			}
			else if(vexRT[Btn6UXmtr2] == 1)
			{
				motor[ChainLeft] = -120;
				motor[ChainRight] = -120;
			}
			else
			{
				motor[ChainLeft] = 0;
				motor[ChainRight] = 0;
			}
		}
	}
