#pragma config(Sensor, in1,    ,               sensorPotentiometer)
#pragma config(Sensor, in2,    ,               sensorPotentiometer)
#pragma config(Sensor, dgtl1,  Wheel,          sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  Mobile,         sensorQuadEncoder)
#pragma config(Motor,  port1,           Claw,          tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           FrontLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           FrontRight,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,           BackLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           BackRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           MogoLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           MogoRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           ChainLeft,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ChainRight,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

//FourBarMovement

	void pre_auton()
	{

		// Set bStopTasksBetweenModes to false if you want to keep user created tasks
		// running between Autonomous and Driver controlled modes. You will need to
		// manage all user created tasks if set to false.
		bStopTasksBetweenModes = true;

		// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
		// used by the competition include file, for example, you might want
		// to display your team name on the LCD in this function.
		// bDisplayCompetitionStatusOnLcd = false;

		// All activities that occur before the competition starts
		// Example: clearing encoders, setting servo positions, ...
	}

	/*---------------------------------------------------------------------------*/
	/*                                                                           */
	/*                              Autonomous Task                              */
	/*                                                                           */
	/*  This task is used to control your robot during the autonomous phase of   */
	/*  a VEX Competition.                                                       */
	/*                                                                           */
	/*  You must modify the code to add your own robot specific commands here.   */
	/*---------------------------------------------------------------------------*/



	task autonomous()
	{
		motor[FrontLeft] = 127;
		motor[FrontRight] = 127;
		motor[BackLeft] = 127;
		motor[BackRight] = 127;
		wait1Msec(4000);
		motor[FrontLeft] = 0;
		motor[FrontRight] = 0;
		motor[BackLeft] = 0;
		motor[BackRight] = 0;
		wait1Msec(100);

	}
	/*---------------------------------------------------------------------------*/
	/*                                                                     */
	/*                              User Control Task                            */
	/*                                                                           */
	/*  This task is used to control your robot during the user control phase of */
	/*  a VEX Competition.                                                       */
	/*                                                                           */
	/*  You must modify the code to add your own robot specific commands here.   */
	/*---------------------------------------------------------------------------*/

	task usercontrol()
	{
		// User control code here, inside the loop

		while (true)
		{
			//Movement
			motor[FrontRight] = (vexRT[Ch3] + vexRT[Ch4]);
			motor[FrontLeft]  = (vexRT[Ch3] - vexRT[Ch4]);
			motor[BackRight] = (vexRT[Ch3] + vexRT[Ch4]);
			motor[BackLeft]  = (vexRT[Ch3] - vexRT[Ch4]);


			//Mogo
			if(vexRT[Btn5U] == 1)
			{
				motor[MogoLeft] = 127;
				motor[MogoRight] = 127;
			}
			else if(vexRT[Btn6U] == 1)
			{
				motor[MogoLeft] = -127;
				motor[MogoRight] = -127;
			}
			else
			{
				motor[MogoLeft] = 0;
				motor[MogoRight] = 0;
			}

			motor[ChainLeft] = (vexRT[Ch3Xmtr2]);
			motor[ChainRight] = (vexRT[Ch3Xmtr2]);


			if(vexRT[Btn5UXmtr2] == 1)
			{
				motor[Claw] = 120;
			}
			else if(vexRT[Btn6UXmtr2] == 1)
			{
				motor[Claw] = -120;
			}
			else
			{
				motor[Claw] = 0;
			}
		}
}
