#pragma config(Sensor, in1,    LeftSensor,     sensorPotentiometer)
#pragma config(Sensor, in2,    RightSensor,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  RightSensor2,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LeftSensor2,    sensorQuadEncoder)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           BackRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           FrontRight,    tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LiftRight,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           LiftRightTwo,  tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           LiftLeftTwo,   tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           LiftLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           FrontBackLeft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

//Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void cogoco()
{
	while(SensorValue(RightSensor2) <  180)
	{
		motor[LiftLeftTwo] = 	-90;
		motor[LiftRightTwo] = 90;
	}
	motor[LiftLeftTwo] = 	0;
	motor[LiftRightTwo] = 0;
}

void cogomo()
{
	while(SensorValue(RightSensor2) > 20)
	{
		motor[LiftLeftTwo] = 90;
		motor[LiftRightTwo] = -90;
	}
	motor[LiftLeftTwo] = 0;
	motor[LiftRightTwo] = 0;
}

void clawopen(int time)
{
	motor[Claw] = -127;
}

void clawclose(int time)
{
	motor[Claw] = 127;
}

//Mobile Goal Go Down While Robot Moves Forward
void mogodownforward(int time)
{
	motor[BackRight] = 90;
	motor[FrontRight] = 90;
	motor[FrontBackLeft] = 90;
	motor[LiftLeft] = 127;
	motor[LiftRight] = 127;
	wait1Msec(time);
	motor[BackRight] = 0;
	motor[FrontRight] = 0;
	motor[FrontBackLeft] = 0;
	motor[LiftLeft] = 0;
	motor[LiftRight] = 0;
}

void mogoupbackward(int time)
{
	motor[BackRight] = -110;
	motor[FrontRight] = -110;
	motor[FrontBackLeft] = -110;
	motor[LiftLeft] = -127;
	motor[LiftRight] = -127;
	wait1Msec(time);
	motor[BackRight] = 0;
	motor[FrontRight] = 0;
	motor[FrontBackLeft] = 0;
	motor[LiftLeft] = 0;
	motor[LiftRight] = 0;
}

//conelift right turn
void cogodown(int time)
{
	motor[LiftLeftTwo] = 70;
	motor[LiftRightTwo]= -70;
	wait1Msec(time);
	motor[LiftLeftTwo] = 0;
	motor[LiftRightTwo]= 0;
}

//conelift left turn
void cogoup(int time)
{
	motor[LiftLeftTwo] = -70;
	motor[LiftRightTwo]= 70;
	wait1Msec(time);
	motor[LiftLeftTwo] = 0;
	motor[LiftRightTwo]= 0;
}

//mobilegoal down
void mogodown(int time)
{
	motor[LiftLeft] = motor[LiftRight] = -110;
	wait1Msec(time);
	motor[LiftLeft] = motor[LiftRight] = 0;
}

//mobilegoal up
void mogoup(int time)
{
	motor[LiftLeft] = motor[LiftRight] = 110;
	wait1Msec(time);
	motor[LiftLeft] = motor[LiftRight] = 0;
}

//move forward
void driveforward(int time)
{
	motor[FrontBackLeft] = 110;
	motor[FrontRight] = 110;
	motor[BackRight] = 110;
	wait1Msec(time);
	motor[FrontRight] = 0;
	motor[BackRight] = 0;
	motor[FrontBackLeft] = 0;
}

//moveforward
void drivebackward(int time)
{
	motor[FrontRight] = -110;
	motor[FrontBackLeft] = -110;
	motor[BackRight] = -110;
	wait1Msec(time);
	motor[FrontRight] = 0;
	motor[BackRight] = 0;
	motor[FrontBackLeft] = 0;
}

//right turn
void right(int time)
{
	motor[FrontRight] = -110;
	motor[FrontBackLeft] = 110;
	motor[BackRight] = -110;
	wait1Msec(time);
	motor[FrontRight] = 0;
	motor[BackRight] = 0;
	motor[FrontBackLeft] = 0;
}


//left turn
void left(int time)
{
	motor[FrontRight] = 110;
	motor[FrontBackLeft] = -110;
	motor[BackRight] = 110;
	wait1Msec(time);
	motor[FrontRight] = 0;
	motor[BackRight] = 0;
	motor[FrontBackLeft] = 0;
}

void matchload()
{
	clawopen(3000);
	wait1Msec(400);
	cogodown(1200);
	wait1Msec(400);
	clawclose(3000);
	cogoup(1200);
	wait1Msec(400);
	clawopen(3000);
}

void mobilegoalten()
{
	cogoup(1500);
	mogodown(1400);
	driveforward(1700);
	mogoup(550);
	cogodown(1500);
	clawopen(100);
	cogoup(400);
	clawclose(80);
	cogoup(1700);
	mogoup(900);
	drivebackward(1800);
	right(350);
	driveforward(100);
	right(800);
	driveforward(400);
	mogodown(1400);
	drivebackward(500);
	mogoup(1400);
}

void mobilegoaltennotsure()
{
		driveforward(200);
		cogoup(1400);
		wait1Msec(1400);
		mogodown(1800);
		wait1Msec(100);
		driveforward(400);
		mogoup(1800);
		drivebackward(900);
		right(250);
		driveforward(150);
		right(400);
		driveforward(500);
		mogodown(1700);
		drivebackward(700);
		mogoup(1700);
}

void stationarygoal()
{
	drivebackward(120);
	cogoup(1680);
	wait1Msec(500);
	clawopen(80);
	wait1Msec(500);
	cogodown(1400);
	driveforward(150);
	clawclose(80);
	motor[FrontRight] = -127;
	motor[FrontBackLeft] = 127;
	motor[BackRight] = -127;
	wait1Msec(500);
	motor[FrontBackLeft] = 127;
	motor[FrontRight] = 127;
	motor[BackRight] = 127;
	wait1Msec(500);
	motor[FrontBackLeft] = 0;
	motor[FrontRight] = 0;
	motor[BackRight] = 0;
	clawclose(80);

}

void trollcode(int time)
{
		driveforward(4000);
		cogoup(800);
		mogodown(1700);
}

	void pre_auton()
	{
		// Set bStopTasksBetweenModes to false if you want to keep user created tasks
		// running between Autonomous and Driver controlled modes. You will need to
		// manage all user created tasks if set to false.
		bStopTasksBetweenModes = true;

		// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
		// used by the competition include file, for example, you might want
		// to display your team name on the LCD in this function.
		// bDisplayCompetitionStatusOnLcd = false;

		// All activities that occur before the competition starts
		// Example: clearing encoders, setting servo positions, ...
	}

	/*---------------------------------------------------------------------------*/
	/*                                                                           */
	/*                              Autonomous Task                              */
	/*                                                                           */
	/*  This task is used to control your robot during the autonomous phase of   */
	/*  a VEX Competition.                                                       */
	/*                                                                           */
	/*  You must modify the code to add your own robot specific commands here.   */
	/*---------------------------------------------------------------------------*/



	task autonomous()
	{
		driveforward(4000);
		cogoup(800);
		mogodown(1700);
	}
	/*---------------------------------------------------------------------------*/
	/*                                                                     */
	/*                              User Control Task                            */
	/*                                                                           */
	/*  This task is used to control your robot during the user control phase of */
	/*  a VEX Competition.                                                       */
	/*                                                                           */
	/*  You must modify the code to add your own robot specific commands here.   */
	/*---------------------------------------------------------------------------*/

	task usercontrol()
	{
		// User control code here, inside the loop

		while (true)
		{
			//Movement
			motor[FrontRight] = (vexRT[Ch3] - vexRT[Ch4]);
			motor[FrontBackLeft]  = (vexRT[Ch3] + vexRT[Ch4]);
			motor[BackRight] = (vexRT[Ch3] - vexRT[Ch4]);

			//Lift
			if(vexRT[Btn5U] == 1)
			{
				motor[LiftLeft] = 127;
				motor[LiftRight] = 127;
			}
			else if(vexRT[Btn6U] == 1)
			{
				motor[LiftLeft] = -127;
				motor[LiftRight] = -127;
			}
			else
			{
				motor[LiftLeft] = 0;
				motor[LiftRight] = 0;
			}

			//Lift2
			if(vexRT[Ch3Xmtr2] == -127)
			{
				motor[LiftRightTwo] = 127;
				motor[LiftLeftTwo] = -127;
			}
			else if(vexRT[Ch3Xmtr2] == 127)
			{
				motor[LiftRightTwo] = -127;
				motor[LiftLeftTwo] = 127;
			}
			else
			{
				motor[LiftLeftTwo] = 0;
				motor[LiftRightTwo] = 0;
			}

			//Claw
			if(vexRT[Btn5UXmtr2] == 1)
			{
				motor[Claw] = 120;
			}
			else if(vexRT[Btn6UXmtr2] == 1)
			{
				motor[Claw] = -120;
			}
			else
			{
				motor[Claw] = 0;
			}

		}
	}
